export const FETCH_TESTS_START = 'FETCH_TESTS_START';
export const FETCH_TESTS_SUCCESS = 'FETCH_TESTS_SUCCESS';
export const FETCH_TESTS_ERROR = 'FETCH_TESTS_ERROR';

export const ADD_TEST_TO_FAVORITES_SUCCESS = 'ADD_TEST_TO_FAVORITES_SUCCESS';
export const ADD_TEST_TO_FAVORITES_ERROR = 'ADD_TEST_TO_FAVORITES_ERROR';

export const ADD_NEW_TEST_SUCCESS = 'ADD_NEW_TEST_SUCCESS';
export const ADD_NEW_TEST_ERROR = 'ADD_NEW_TEST_ERROR';

export const REMOVE_TEST_SUCCESS = 'REMOVE_TEST_SUCCESS';
export const REMOVE_TEST_ERROR = 'REMOVE_TEST_ERROR';

export const EDIT_TEST_SUCCESS = 'EDIT_TEST_SUCCESS';
export const EDIT_TEST_ERROR = 'EDIT_TEST_ERROR';

export const CREATE_QUIZ_QUESTION = 'CREATE_QUIZ_QUESTION';
export const RESET_QUIZ_CREATION = 'RESET_QUIZ_CREATION';
