export const FETCH_TESTS_START = 'FETCH_TESTS_START';
export const FETCH_TESTS_SUCCESS = 'FETCH_TESTS_SUCCESS';
export const FETCH_TESTS_ERROR = 'FETCH_TESTS_ERROR';

export const ADD_TEST_TO_FAVORITES_SUCCESS = 'ADD_TEST_TO_FAVORITES_SUCCESS';
export const ADD_TEST_TO_FAVORITES_ERROR = 'ADD_TEST_TO_FAVORITES_ERROR';

export const ADD_NEW_TEST_SUCCESS = 'ADD_NEW_TEST_SUCCESS';
export const ADD_NEW_TEST_ERROR = 'ADD_NEW_TEST_ERROR';
export const REMOVE_TEST_SUCCESS = 'REMOVE_TEST_SUCCESS';
export const REMOVE_TEST_ERROR = 'REMOVE_TEST_ERROR';

export const REMOVE_QUIZ_ERROR = 'REMOVE_QUIZ_ERROR';
export const REMOVE_QUIZ_SUCCESS = 'REMOVE_QUIZ_SUCCESS';
export const COPY_QUIZ_SUCCESS = 'COPY_QUIZ_SUCCESS';
export const COPY_QUIZ_ERROR = 'COPY_QUIZ_ERROR';
export const EDIT_TEST_SUCCESS = 'EDIT_TEST_SUCCESS';
export const EDIT_TEST_ERROR = 'EDIT_TEST_ERROR';

export const ADD_NEW_QUIZ_START = 'ADD_NEW_QUIZ_START';
export const ADD_NEW_QUIZ_SUCCESS = 'ADD_NEW_QUIZ_SUCCESS';
export const ADD_NEW_QUIZ_ERROR = 'ADD_NEW_QUIZ_ERROR';

export const CREATE_QUIZ_QUESTION = 'CREATE_QUIZ_QUESTION';
export const SET_QUIZ_NAME = 'SET_QUIZ_NAME';

export const FETCH_QUIZES_START = 'FETCH_QUIZES_START';
export const FETCH_QUIZES_SUCCESS = 'FETCH_QUIZES_SUCCESS';
export const FETCH_QUIZES_ERROR = 'FETCH_QUIZES_ERROR';

export const FETCH_QUIZ_START = 'FETCH_QUIZ_START';
export const FETCH_QUIZ_SUCCESS = 'FETCH_QUIZ_SUCCESS';
export const FETCH_QUIZ_ERROR = 'FETCH_QUIZ_ERROR';

export const QUIZ_SET_STATE = 'QUIZ_SET_STATE';
export const QUIZ_FINISH = 'QUIZ_FINISH';
export const QUIZ_NEXT_QUESTION = 'QUIZ_NEXT_QUESTION';
export const QUIZ_RETRY = 'QUIZ_RETRY';

export const START_TIMER = 'START_TIMER';
export const STOP_TIMER = 'STOP_TIMER';
export const TICK_TIMER = 'TICK_TIMER';

export const RESET = 'RESET';
